allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.110.4'
  - '@supabase/functions-js@2.110.4'
  - '@supabase/postgrest-js@2.110.4'
  - '@supabase/realtime-js@2.110.4'
  - '@supabase/ssr@0.12.1'
  - '@supabase/storage-js@2.110.4'
  - '@supabase/supabase-js@2.110.4'
